server:
  port: ${ufosadapter.http.port}

spring:
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: ufosadapter
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/

routes:
  log: ${camel.endpoint.logging}
  ftp:
#    server: ftp://ftp:${ftp.port}
    port: ${ftp.port}
    user: ${ftp.username}
    pass: ${ftp.password}
  toUfos:
    inboundQueue: ${ufosadapter.routes.toUfos.inbound}
    outboundQueue: ${ufosadapter.routes.toUfos.outbound}
  fromUfos:
    inboundQueue: ${ufosadapter.routes.fromUfos.inbound}
    outboundQueue: ${smev3core.routes.Vis2Smev.preprocessor.inbound}
  callback:
    inbound:
      inputQueue: ${ufosadapter.routes.fromUfos.callback.inbound}
      #bpmnQueue: ${}
    outbound:
      #bpmnQueue: ${}
      outboundQueue: ${ufosadapter.routes.fromUfos.callback.outbound}
