server:
  port: ${smev3core.http.port}

spring:
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: smev3core
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/

routes:
  log: ${camel.endpoint.logging}
  Smev2Vis:
    preprocessor:
      GetRequestResponseQueue: ${smev3core.routes.Smev2Vis.preprocessor.inbound.GetRequestResponseQueue}
      GetResponseResponseQueue: ${smev3core.routes.Smev2Vis.preprocessor.inbound.GetResponseResponseQueue}
    postprocessor:
      inbound: ${smev3core.routes.Smev2Vis.postprocessor.inbound}
    GetStatusResponseQueue: ${smev3core.routes.Smev2Vis.GetStatusResponseQueue}
  Vis2Smev:
    pushers: ${pushers.routes.vis2smev.inbound}
    preprocessor:
      inboundQueue: ${smev3core.routes.Vis2Smev.preprocessor.inbound}
  slipEndpoints:
    STUB: ${ufosadapter.routes.toUfos.inbound}
    UFOS: ${ufosadapter.routes.toUfos.inbound}
  smev3adapter: http://smev3adapter:${smev3adapter.http.port}/camel/request
