server:
  port: ${pushers.http.port}

spring:
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: pushers
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/

routes:
  log: ${camel.endpoint.logging}
  smev3adapter: http://smev3adapter:${smev3adapter.http.port}/camel/request
  vis2smev:
    inbound: ${pushers.routes.vis2smev.inbound}