server:
  port: ${replication.http.port}

spring:
  activemq:
    brokerUrl: ${activemq.url}
    inMemory: false
    user: ${activemq.username}
    password: ${activemq.password}
    pool:
      enabled: true
      max-connections: 10
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: replication
#  jta:
#    narayana:
#      default-timeout: 10 #3600000

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/

routes:
  log: ${camel.endpoint.logging}
  replicationService:
    inboundQueue: ${replication.routes.replicationService.inbound.queue}
    outboundQueue: ${smev3core.routes.Smev2Vis.postprocessor.inbound}
  ftp: ftp://ftp:${ftp.port}/replication?username=${ftp.username}&password=${ftp.password}&disconnect=true&passiveMode=true
  smev: ftp://${smev3mock2.ftp.host}:${smev3mock2.ftp.port}
