server:
  port: ${replication.http.port}

spring:
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: replication
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/

routes:
  log: ${camel.endpoint.logging}
  replicationService:
    inboundQueue: ${replication.routes.replicationService.inbound.queue}
    outboundQueue: ${smev3core.routes.Smev2Vis.postprocessor.inbound}
  ftp: ftp://ftp:${ftp.port}/replication?username=${ftp.username}&password=${ftp.password}&disconnect=true&passiveMode=true
  smev: ftp://${smev3mock2.ftp.host}:${smev3mock2.ftp.port}
