server:
  port: ${replication.http.port}

spring:
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: replication
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/

routes:
  log: ${camel.endpoint.logging}
  smev2vis:
    inboundQueue: ${replication.routes.replicationService.smev2vis.inbound.queue}
    outboundQueue: ${smev3core.routes.Smev2Vis.postprocessor.inbound}
    ftpsmev: ftp://${smev.ftp.host}:${smev.ftp.port}
    ftp: ftp://ftp:${ftp.port}/replication?username=${ftp.username}&password=${ftp.password}&disconnect=true&passiveMode=true
  vis2smev:
    inboundQueue: ${replication.routes.replicationService.vis2smev.inbound.queue}
    outboundQueue: ${smev3core.routes.Vis2Smev.postprocessor.inbound}
    ftpvis: ftp://${ftp.host}:${ftp.port}/ufos?username=${ftp.username}&password=${ftp.password}&disconnect=true&passiveMode=true
    ftpsmev: ftp://${smev.ftp.host}:${smev.ftp.port}/inbox?username=${smev.ftp.username}&password=${smev.ftp.password}&disconnect=true&passiveMode=true