version: '2'

services:
  activemq:
    image: webcenter/activemq:latest
    restart: always
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613

  smev3core:
    image: smev3client/smev3core
    restart: never
    ports:
      - 5005:5005
#    logging:
#      driver: "gelf"
#      options:
#        gelf-address: "udp://localhost:12201"
#        tag: "ufosadapter"
