spring:
  profiles: dev
  activemq:
    brokerUrl: ${activemq.url}
    inMemory: false
    user: ${activemq.username}
    password: ${activemq.password}
    pool:
      enabled: true

  devtools:
    remote:
      secret: ${devtools.secret}

server:
   port: ${smev3adapter.http.port}

operations:
  - Ack
  - GetIncomingQueueStatistics
  - GetRequest
  - GetStatus
  - SendRequest
  - SendResponse

smevServiceNamespace: urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1

namespaceMappings:
  http://otr.ru/irs/services/message-exchange/types : urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1
  http://otr.ru/irs/services/message-exchange/types/basic : urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

routes:
  log: ${smev3adapter.routes.log}