spring:
 profiles: dev
 activemq:
     brokerUrl: ${activemq.url}
     inMemory: false
     user: ${activemq.username}
     password: ${activemq.password}
     pool:
       enabled: true
 devtools:
     remote:
       secret: ${devtools.secret}

server:
   port: ${pollers.host.port}

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: true

smev3adapter:
   host:
     port: ${smev3adapter.host.port}