spring:
 profiles: dev
 activemq:
     brokerUrl: ${activemq.url}
     inMemory: false
     user: ${activemq.username}
     password: ${activemq.password}
     pool:
       enabled: true
 devtools:
     remote:
       secret: ${devtools.secret}

server:
   port: ${pollers.http.port}

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: true

smev3adapter:
   http:
     port: ${smev3adapter.http.port}

routes:
  GetRequestPoller:
    GetRequestResponseQueue: ${smev3core.routes.Smev2Vis.preprocessor.inbound.GetRequestResponseQueue}
  GetResponsePoller:
    GetResponseResponseQueue: ${smev3core.routes.Smev2Vis.preprocessor.inbound.GetResponseResponseQueue}
  GetStatusPoller:
    GetStatusResponseQueue: ${smev3core.routes.Smev2Vis.preprocessor.inbound.GetStatusResponseQueue}