server:
  port: ${bpmengine.http.port}

spring:
  activemq:
    brokerUrl: ${activemq.url}
    inMemory: false
    user: ${activemq.username}
    password: ${activemq.password}
    pool:
      enabled: true
      configuration:
        max-connections: 100
        maximum-active-session-per-connection: 10
  devtools:
    remote:
      secret: ${devtools.secret}
  jta:
    bitronix:
      connectionfactory:
        min-pool-size: 10
        max-pool-size: 100
  application:
    name: bpmengine
  datasource:
    url: jdbc:postgresql://postgresql:5432/activiti
    username: ${bpmengine.db.username}
    password: ${bpmengine.db.password}
    driverClassName: org.postgresql.Driver
  activiti:
    db-history-used: true
    history-level: full

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/