spring:
  profiles: dev
  activemq:
    brokerUrl: ${activemq.url}
    inMemory: false
    user: ${activemq.username}
    password: ${activemq.password}
    pool:
      enabled: true

  devtools:
    remote:
      secret: ${devtools.secret}

server:
   port: ${replication.http.port}

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

routes:
  replicationService:
    inboundQueue: ${replication.routes.replicationService.inbound.queue}
    outboundQueue: ${smev3core.routes.postprocessor.inbound}
    log: ${replication.routes.replicationService.log}