server:
   port: ${smev3adapter.http.port}

spring:
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: smev3adapter
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

operations:
  - Ack
  - GetIncomingQueueStatistics
  - GetStatus
  - SendRequest
  - GetRequest
  - SendResponse
  - GetResponse

smevServiceNamespace: urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1

namespaceMappings:
  http://otr.ru/irs/services/message-exchange/types : urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1
  http://otr.ru/irs/services/message-exchange/types/basic : urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/

routes:
  log: ${camel.endpoint.logging}
