server:
  port: ${ufosadapter.http.port}

spring:
  activemq:
    brokerUrl: ${activemq.url}
    inMemory: false
    user: ${activemq.username}
    password: ${activemq.password}
    pool:
      enabled: true
      configuration:
        max-connections: 100
        maximum-active-session-per-connection: 10
  devtools:
    remote:
      secret: ${devtools.secret}
  jta:
    bitronix:
      connectionfactory:
        min-pool-size: 10
        max-pool-size: 100
#    atomikos:
#      connectionfactory:
#        min-pool-size: 10
#        max-pool-size: 100
#      properties:
#        console-log-level: debug

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

routes:
  toUfos:
    inboundQueue: ${ufosadapter.routes.toUfos.inbound.queue}
    outboundQueue: ${ufosadapter.routes.toUfos.outbound.queue}
    log: ${ufosadapter.routes.toUfos.log}