package ru.otr.integration.smev3client.config;

import javax.xml.ws.Endpoint;

import org.apache.cxf.Bus;
import org.apache.cxf.bus.spring.SpringBus;
import org.apache.cxf.jaxws.EndpointImpl;
import org.apache.cxf.transport.servlet.CXFServlet;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import ru.it.smev.message_exchange.autogenerated.service.v1_2.SMEVMessageExchangePortType;
import ru.otr.integration.smev3client.endpoint.SMEVMessageExchangeServiceEndpoint;

/**
 * Created by tartanov.mikhail on 09.08.2016.
 */


@Configuration
public class WebServiceConfiguration {


    @Bean
    public ServletRegistrationBean dispatcherServlet() {
        return new ServletRegistrationBean(new CXFServlet(), "/soap-api/*");
    }

    @Bean(name = Bus.DEFAULT_BUS_ID)
    public SpringBus springBus() {
        return new SpringBus();
    }

    @Bean
    public SMEVMessageExchangePortType smevMessageExchangeService() {
        return new SMEVMessageExchangeServiceEndpoint();
    }

    @Bean
    public Endpoint endpoint() {
        EndpointImpl endpoint = new EndpointImpl(springBus(), smevMessageExchangeService());
        endpoint.publish("/SmevMessageExchangeService");
        endpoint.setWsdlLocation("smev-message-exchange-service-1.1.wsdl");
        return endpoint;
    }
}
