spring:
  profiles: dev
  activemq:
    brokerUrl: ${activemq.url}
    inMemory: false
    user: ${activemq.username}
    password: ${activemq.password}
    pool:
      enabled: true
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: smev3mock2

server:
   port: ${smev3mock2.http.port}


camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

ftp:
   user:  ${smev3mock2.ftp.user}
   password: ${smev3mock2.ftp.password}
   port: ${smev3mock2.ftp.port}