spring:
  profiles: dev
  devtools:
    remote:
      secret: ${devtools.secret}
  application:
    name: smev3mock2

server:
   port: ${smev3mock2.http.port}


camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: false

ftp:
   host: ${smev3mock2.ftp.host}
   user: ${smev3mock2.ftp.user}
   password: ${smev3mock2.ftp.password}
   port: ${smev3mock2.ftp.port}