spring:
  profiles: dev
  activemq:
#    brokerUrl: tcp://localhost:61616
    brokerUrl: ${activemq.url}
    inMemory: false
#    user: admin
    user: ${activemq.username}
#    password: admin
    password: ${activemq.password}
    pool:
      enabled: true
  devtools:
    remote:
      secret: ${devtools.secret}

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: true

routes:
  preprocessor:
    inbound:
      ${smev3core.routes.preprocessor.inbound}
    outbound:
      default:
        ${smev3core.routes.preprocessor.outbound.default}
      replication:
        ${smev3core.routes.preprocessor.outbound.replication}
  postprocessor:
    inbound:
      ${smev3core.routes.postprocessor.inbound}
    outbound:
      default:
        ${smev3core.routes.postprocessor.outbound.default}
  metadata:
    STUB:
      ${smev3core.routes.STUB.outbound}
    test:
      ${smev3core.routes.STUB.outbound}
