server:
  port: ${smev3core.http.port}

spring:
  profiles: dev
  activemq:
    brokerUrl: ${activemq.url}
    inMemory: false
    user: ${activemq.username}
    password: ${activemq.password}
    pool:
      enabled: true
  devtools:
    remote:
      secret: ${devtools.secret}

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching: true

routes:
  preprocessor:
    inbound: ${smev3core.routes.preprocessor.inbound}
    GetRequestResponseQueue: ${smev3core.routes.preprocessor.inbound.GetRequestResponseQueue}
    GetResponseResponseQueue: ${smev3core.routes.preprocessor.inbound.GetResponseResponseQueue}
    replication: ${replication.routes.replicationService.inbound.queue}
  postprocessor:
    inbound: ${smev3core.routes.postprocessor.inbound}
  metadata:
    STUB: ${ufosadapter.routes.toUfos.inbound.queue}
    UFOS: ${ufosadapter.routes.toUfos.inbound.queue}
  GetStatusResponseQueue: ${smev3core.routes.preprocessor.inbound.GetStatusResponseQueue}
  log: ${smev3core.routes.log}