spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: ${configserver.http.port}

security:
  user:
    password: ${configserver.password}