server:
  port: ${configserver.http.port}

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  application:
    name: configserver

security:
  user:
    password: ${configserver.password}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:${eureka.http.port}/eureka/
